# Generated by Django 5.1.1 on 2024-10-12 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupones',
            fields=[
                ('id_cupon', models.AutoField(primary_key=True, serialize=False)),
                ('cupon', models.CharField(max_length=10)),
                ('porcentaje_descuento', models.IntegerField()),
                ('usos_maximos', models.IntegerField()),
                ('usos_disponibles', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'cupones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField()),
                ('tipo_pedido', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_cupon', models.ForeignKey(blank=True, db_column='id_cupon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.cupones')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='clients.usuarios')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='products.productos')),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='orders.pedidos')),
            ],
            options={
                'db_table': 'detalle_pedido',
            },
        ),
    ]
